### ISSUE TITLE
show popup on torrent DL finish even when seeding is active

### ISSUE THREAD

**Issue by dwatzke** [LubosD/fatrat#13]
Hi,

currently fatrat shows a popup about a finished transfer only when a transfer reaches the "completed" state - but in case of torrents, this means that user doesn't get informed about a finished transfer until the pre-set ratio of seeding is reached (if seeding is enabled). This kind of sucks and I think that there should be two popups - one when the content of a torrent is downloaded and another one when the seeding is finished.

Thanks!

**Comment by dwatzke** [comment]
Here's a patch that fixes this:

https://github.com/dwatzke/fatrat/commit/dabb6f05614f8d1726c8c5c772fbe2b2707d5e9a

**Comment by dwatzke** [comment]
By the way, there's a small defect when you apply the patch - fatrat shows the "download finished, starting upload now" message after startup for torrent transfers that are in the seeding mode.  Maybe the status-change-notification-signals should be connected _after_ the transfers are loaded and initialized at startup.

**Comment by LubosD** [comment]
Merged.
