### ISSUE TITLE
square brackets in URL encode improperly on save and load

### ISSUE THREAD

**Issue by CTrauma** [LubosD/fatrat#20]
This causes a url with [] to be encoded and saved and then re-encoded on load so that the URL becomes invalid and you get a failed download.

so [test] becomes %5Btest%5D which becomes %255Btest%255D

My current workaround is to use change line 252 in CurlDownload.cpp to use url.url.toString() instead of url.url.toEncoded()

I didn't have time to research if this is the correct fix or not, but for now everything is working as needed.

**Comment by LubosD** [comment]
You are right, since the loading code doesn't urldecode the persisted URL.
