### ISSUE TITLE
make install error

### ISSUE THREAD

**Issue by maxdevaine** [LubosD/fatrat#22]
cmake . \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DWITH_DOCUMENTATION=ON \
        -DWITH_NLS=ON \
        -DWITH_CURL=ON \
        -DWITH_BITTORRENT=ON
  make
...
make install
...
-- Installing: /tmp/yaourt-tmp-max/aur-fatrat-git/pkg/fatrat-git/usr/share/fatrat/data/bttrackers.txt
CMake Error at cmake_install.cmake:143 (file):
  file INSTALL cannot find
  "/tmp/yaourt-tmp-max/aur-fatrat-git/src/fatrat/doc/fatrat.qhc".

**Comment by vdemin** [comment]
Seems you try to install 1.2.0_beta2-1 from AUR. Please look at my comment:
https://aur.archlinux.org/packages/fatrat/?comments=all
qt4 version of fatrat incorrectly detect where the qcollectiongenerator tool is.

**Comment by pmattern** [comment]
Regarding AUR package fatrat-git which you're apparently trying to compile the only way to reproduce your findings was some rather insane tweaking like removing qtchooser by `pacman -Rdd` or setting a default Qt version that isn't installed at all.
But as long as qtchooser which is pulled via dependency qt5-tools is set up reasonably, e. g. by not changing anything, the package is building flawlessly both on i686 and x86_64 here.
Any chance you changed something as stated above by incident?

**Comment by maxdevaine** [comment]
You are right,
qtchooser not working :
qmake: could not find a Qt installation of ''

$ ls -l /usr/bin/qmake*
lrwxrwxrwx 1 root root  9 13. pro  2014 /usr/bin/qmake -> qtchooser
lrwxrwxrwx 1 root root 22 16. čec 06.24 /usr/bin/qmake-qt4 -> /usr/lib/qt4/bin/qmake
lrwxrwxrwx 1 root root 21 18. srp 09.21 /usr/bin/qmake-qt5 -> /usr/lib/qt/bin/qmake

command :
$ qtchooser -l
show nothing.

$ ls -l /etc/xdg/qtchooser/
celkem 12
lrwxrwxrwx 1 root root 25 13. pro  2014 default.conf -> /etc/xdg/qtchooser/5.conf
-rw-r--r-- 1 root root 26 13. pro  2014 4.conf
-rw-r--r-- 1 root root 25 13. pro  2014 5.conf

both config files is ok :
$ cat /etc/xdg/qtchooser/4.conf
/usr/lib/qt4/bin
/usr/lib

$ cat /etc/xdg/qtchooser/5.conf 
/usr/lib/qt/bin
/usr/lib

and this was strange too :

$ export QT_SELECT=4
$ qmake --help
qmake: could not find a Qt installation of '4'

$ export QT_SELECT=5
$ qmake --help
qmake: could not find a Qt installation of '5'


This solution working :
qtchooser -install 4 /usr/lib/qt4/bin/qmake 
qtchooser -install 5 /usr/lib/qt/bin/qmake

this commands create :
~/.config/qtchooser/5.conf
~/.config/qtchooser/4.conf

and with this :
qtchooser -l

show both version now.

with 
export QT_SELECT=5
working qtchooser too


So, qtchooser not respect global configuration files in :
/etc/xdg/qtchooser/


I was found this source code :
https://github.com/qtproject/qtchooser
https://github.com/qtproject/qtchooser/blob/master/src/qtchooser/main.cpp

I'm not a programmer, so I do not understand how it exactly works, but I found this code :
qgetenv("XDG_CONFIG_HOME", userHome() + PATH_SEP ".config");

and this is the problem, environment variable "XDG_CONFIG_HOME" is not defined. So, qtchooser not know, where is "/etc/xdg" dir.

If I use this :
XDG_CONFIG_HOME=/etc/xdg qtchooser -l
all works ...


Final solution for me is :
qtchooser -install 4 /usr/lib/qt4/bin/qmake 
qtchooser -install 5 /usr/lib/qt/bin/qmake
cd ~/.config/qtchooser/
ln -s 5.conf default.conf

Now compilation and installtion works ok.

Max

**Comment by pmattern** [comment]
While it's fine that you can compile and use package `fatrat-git` now your findings strongly suggest there's something wrong on your system:

In freedesktop.org's [Base Directory Specification](http://www.freedesktop.org/wiki/Specifications/basedir-spec/) you can see that there are two environment variables `XDG_CONFIG_{DIRS,HOME}` which name root directories of configuration affecting the local system as a whole and per user respectively. Those environment variables should either be set or `/etc/xdg` and `~/.config` should be used as fallback by default. Both is taking place on my local system. E. g. in an LXQt session both are set
```
$ env | grep XDG_CONFIG 
XDG_CONFIG_DIRS=/etc/xdg
XDG_CONFIG_HOME=/home/peter/.config
```
In a KDE Plasma 5 session they aren't set
```
$ env | grep XDG_CONFIG
$ 
```
but qtchooser which is looking in both fallback locations stated above, see section "Files" in man qtchooser, knows where to look for nevertheless
```
$ qtchooser -l
4
5
default
```

What you did is first create the user-specific directory which doesn't exist by default and then have the user-spefic environment variable point to the system-wide directory. The latter is not only counteracting the former but also plain wrong.
The actual problem at your side is the set-up of those environment variables, IMO. On the one hand it would be interesting to know how come and on the other hand it's likely that this will bite you with regards to other applications, too.

**Comment by maxdevaine** [comment]
Complete solved.
major problem was on the workaround (or historical solution) with this file :
/etc/profile.d/kde4.sh

export KDEDIR=/usr
export KDEDIRS=$KDEDIR:/usr
export PATH=$PATH:$KDEDIR/bin 
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$KDEDIR/lib/pkgconfig
if [ ! -z $XDG_DATA_DIRS ]; then 
  export XDG_DATA_DIRS=$XDG_DATA_DIRS:$KDEDIR/share 
else 
  export XDG_DATA_DIRS=$KDEDIR/share 
fi 
if [ ! -z $XDG_CONFIG_DIRS ]; then 
  export XDG_CONFIG_DIRS=$XDG_CONFIG_DIRS:$KDEDIR/etc/xdg 
else 
  export XDG_CONFIG_DIRS=$KDEDIR/etc/xdg 
fi


This file was workaround for some problems in long time age (I think year 2011).

And otherwise, with kde4.sh file does not working KDE5 (only black screen with mouse cursor).
At this time this file does not needed.

So, now is all ok.
