### ISSUE TITLE
After program is closed, settings revert to default settings. 

### ISSUE THREAD

**Issue by linlinxza** [LubosD/fatrat#29]
This happens on Linux Mint if whenever the program is closed. Is there a fix for this?

**Comment by LubosD** [comment]
There must be something broken with your installation, because it works just fine. Settings are saved into ~/.config/Dolezel/fatrat.conf

**Comment by linlinxza** [comment]
So just reinstall it? Alright. Because all it get in the conf file is this nothing else:

[extensions]
jvm_path=/usr/lib/jvm/java-7-openjdk-i386/jre/lib/i386/server/libjvm.so

**Comment by linlinxza** [comment]
So just reinstall it? Alright. Because all it get in the conf file is this nothing else:

[extensions]
jvm_path=/usr/lib/jvm/java-7-openjdk-i386/jre/lib/i386/server/libjvm.so

**Comment by LubosD** [comment]
This isn't Windows, reinstallation will hardly fix anything. It more sounds like there may be something wrong with your Qt packages.

**Comment by linlinxza** [comment]
So... I'll just update them in the software manager? Yeah,  I am still thinking on a windows basis. But I'm planning to drop it sometime in favour of linux as my main OS.

**Comment by LubosD** [comment]
I don't know, I can't provide support for your distribution. I've just checked with the latest Git code and I see no issues.

**Comment by linlinxza** [comment]
Well, I'll take your word for it; as I can't code to save life. I can only build simple website in HTML and Css. Anyway,  thanks.

**Comment by linlinxza** [comment]
Well, I'll take your word for it; as I can't code to save my life. I can only build simple website in HTML and Css. Anyway, thanks.

**Comment by linlinxza** [comment]
Oh,  can you tell me what Qt packages are required?

**Comment by linlinxza** [comment]
Can you please tell me how to fix the issue with the QT packages or even direct me elsewhere?

**Comment by linlinxza** [comment]
Never mind. The conf file has information of the setting written to it. It's working now after much prodding. :)

But really consider getting an app designed for this manager as I use a an android device to control my media center. Or if you already have something that will work for that purpose please refer me to it. 

I think this download manager brilliant. Especially on a media center.

**Comment by LubosD** [comment]
I also have to use the clumsy web interface on my Android device. I do have the skills to write an Android app for this, but lack the time :-(

**Comment by linlinxza** [comment]
ざんねんだな。。。(That's too bad.)
