### ISSUE TITLE
Current code incompatible with g++ 6

### ISSUE THREAD

**Issue by pmattern** [LubosD/fatrat#32]
Current VCS code is incompatible with changes introduced in g++ 6.

Compiling using that version fails at least with some of the available CMake options like e. g. `-DWITH_BITTORRENT=ON`. Problem does not get manifest using no CMake options at all, `-DCMAKE_INSTALL_PREFIX=/usr`, `-DWITH_DOCUMENTATION=ON`, `-DWITH_NLS=ON` or `-DWITH_CURL=ON`.

Seen compiling fb0e0db on up to date Arch Linux. Output of make uploaded at https://gist.github.com/pmattern/14a8dbcb2be8bc867ca2fe446486b3a8.

On a side note there are some warnings about incompatibility with C++ 11 while compiling which don't cause failure but seem to be worth having a look at nevertheless.

**Comment by LubosD** [comment]
Current master code should hopefully build. Please reopen if that's not the case.

**Comment by pmattern** [comment]
Confirmed. 3980d4e is building flawlessly again and those error messages about C++ 11 have gone as well.
