### ISSUE TITLE
Current code incompatible with libtorrent (Rasterbar) 1.1

### ISSUE THREAD

**Issue by pmattern** [LubosD/fatrat#35]
Current code isn't compatible with version 1.1 of libtorrent (Rasterbar).

Building fails with

```
[ 54%] Building CXX object CMakeFiles/fatrat.dir/src/TransfersModel.cpp.o
/usr/local/peter/Tests/FatRat/Projekt/fatrat/src/TransfersModel.cpp: In member function 'virtual void ProgressDelegate::paint(QPainter*, const QStyleOptionViewItem&, const QModelIndex&) const':
/usr/local/peter/Tests/FatRat/Projekt/fatrat/src/TransfersModel.cpp:381:29: warning: 'QStyleOptionProgressBarV2' is deprecated [-Wdeprecated-declarations]
QStyleOptionProgressBarV2 opts;
                          ^~~~
In file included from /usr/include/qt/QtWidgets/qabstractitemdelegate.h:44:0,
from /usr/include/qt/QtWidgets/qabstractitemview.h:46,
from /usr/include/qt/QtWidgets/qtreeview.h:43,
from /usr/include/qt/QtWidgets/QTreeView:1,
from /usr/local/peter/Tests/FatRat/Projekt/fatrat/src/TransfersModel.h:32,
from /usr/local/peter/Tests/FatRat/Projekt/fatrat/src/TransfersModel.cpp:33:
/usr/include/qt/QtWidgets/qstyleoption.h:337:51: note: declared here
typedef Q_DECL_DEPRECATED QStyleOptionProgressBar QStyleOptionProgressBarV2;
                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~
[ 54%] Building CXX object CMakeFiles/fatrat.dir/src/Logger.cpp.o
In file included from /usr/local/peter/Tests/FatRat/Projekt/fatrat/src/Transfer.cpp:33:0:
/usr/local/peter/Tests/FatRat/Projekt/fatrat/src/engines/TorrentDownload.h:138:29: error: field 'm_status' has incomplete type 'libtorrent::torrent_status'
libtorrent::torrent_status m_status;
                           ^~~~~~~~
In file included from /usr/include/libtorrent/session_handle.hpp:38:0,
from /usr/include/libtorrent/session.hpp:53,
from /usr/local/peter/Tests/FatRat/Projekt/fatrat/src/engines/TorrentDownload.h:43,
from /usr/local/peter/Tests/FatRat/Projekt/fatrat/src/Transfer.cpp:33:
/usr/include/libtorrent/torrent_handle.hpp:72:9: note: forward declaration of 'struct libtorrent::torrent_status'
struct torrent_status;
       ^~~~~~~~~~~~~~
[ 54%] Building CXX object CMakeFiles/fatrat.dir/src/XmlRpc.cpp.o
make[2]: *** [CMakeFiles/fatrat.dir/build.make:1521: CMakeFiles/fatrat.dir/src/Transfer.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:100: CMakeFiles/fatrat.dir/all] Error 2 
make: *** [Makefile:128: all] Error 2
```

but succeeds after downgrading to 1.0.9 (or dropping CMake variable `-DWITH_BITTORRENT=ON`).

**Comment by dwatzke** [comment]
apparently it's just that torrent_status got separated into its own header: https://github.com/arvidn/libtorrent/commit/b628692223d56eff10d7c3610b7e114c0054d388#diff-c3767f909ed6ff3dddc35de3a76e2e67

so just #include <libtorrent/torrent_status.hpp> and you're good...

unfortunately this is not the only thing though... seems there's more of the same in other classes (torrent_info, lazy_entry) and some renamed methods etc.

**Comment by LubosD** [comment]
Sadly, Gentoo is still stuck at 1.0.9. I wish its developer would rather focus on fixing bugs than constantly reworking the APIs.

**Comment by pmattern** [comment]
> I wish libtorrent's developer would rather focus on fixing bugs than constantly reworking the APIs.

I cannot really judge the technical details. But if an imbalance between introduction of new features and fixing existing bugs is impairing the usage of the library I for one think opening an issue about this could very well be appropriate.

**Comment by dwatzke** [comment]
Here's what I managed to do (I'm not sure if everything's correct, especially the chrono time conversion needs to be tested):
[fatrat-rb11.txt](https://github.com/LubosD/fatrat/files/344523/fatrat-rb11.txt)

Note that HasherThread::run() in src/tools/CreateTorrentDlg.cpp is commented out because I don't know how to port it (we can take care of that later)

The problem is that although everything compiles after you apply my patch, the final linking fails with

CMakeFiles/fatrat.dir/src/engines/moc_TorrentPeersModel.cpp.o: In function \`__static_initialization_and_destruction_0(int, int)':
/usr/include/boost/asio/error.hpp:261: undefined reference to \`boost::asio::error::get_netdb_category()'

and similiar errors. I've tried to grep the boost libs to see which one defines these but although I have added -lboost_log and -lboost_log_setup it didn't help at all. Not sure what it's missing :/

**Comment by LubosD** [comment]
It should hopefully build, at least it did on Debian Testing. There are many warnings about deprecated API usage, which I'll fix later.

**Comment by pmattern** [comment]
Confirming both. 3f34e47 is compiling on Arch Linux with BitTorrent enabled again, but the compiler throws a bunch of warnings about libtorrent-rasterbar. Also, at first glance there are now problems when FatRat is running.

**Comment by LubosD** [comment]
Warnings are expected. What problems are you referring to? Could you file bug reports?

**Comment by pmattern** [comment]
Just a bloody typo. Fixed...
